///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Sun Oct 30 2016 21:21:44]
// Generate from:
//   [github.com/vipally/gx/fs/tree.gp_filehash38b3.go]
//   [github.com/vipally/gx/fs/tree.gpg] [tree_filehash]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
//
///////////////////////////////////////////////////////////////////

//this file is used to import by other gp files
//it cannot use independently, simulation C++ stl functors
package fs

type CmpFuncFileHash func(left, right FileHash) bool

//create cmp object by name
func GetCmpFuncFileHash(cmpName string) (r CmpFuncFileHash) {
	switch cmpName {
	case "": //default Lesser
		fallthrough
	case "Lesser":
		r = LessFileHash
	case "Greater":
		r = GreatFileHash
	default: //unsupport name
		panic(cmpName)
	}
	return
}

//Lesser
func LessFileHash(left, right FileHash) (ok bool) {

	ok = left.Less(right)

	return
}

//Greater
func GreatFileHash(left, right FileHash) (ok bool) {

	ok = right.Less(left)

	return
}
