///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Sun Oct 30 2016 17:19:13]
// Generate from:
//   [github.com/vipally/gx/fs/tree.gp_filehash.go]
//   [github.com/vipally/gx/fs/tree.gpg] [tree_filehash]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
//
///////////////////////////////////////////////////////////////////

//this file is used to import by other gp files
//it cannot use independently, simulation C++ stl functors
package fs

type ComparerFileHash interface {
	F(left, right FileHash) bool
}

//create cmp object by name
func CreateComparerFileHash(cmpName string) (r ComparerFileHash) {
	switch cmpName {
	case "": //default Lesser
		fallthrough
	case "Lesser":
		r = LesserFileHash{}
	case "Greater":
		r = GreaterFileHash{}
	default: //unsupport name
		panic(cmpName)
	}
	return
}

//Lesser
type LesserFileHash struct{}

func (this LesserFileHash) F(left, right FileHash) (ok bool) {

	ok = left.Less(right)

	return
}

//Greater
type GreaterFileHash struct{}

func (this GreaterFileHash) F(left, right FileHash) (ok bool) {

	ok = right.Less(left)

	return
}
