///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Sun Oct 30 2016 09:38:59]
// Generate from:
//   [github.com/vipally/gx/fs/tree.gp_filehash.go]
//   [github.com/vipally/gx/fs/tree.gpg] [tree_filehash]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
//
///////////////////////////////////////////////////////////////////

//this file is used to import by other gp files
//it cannot use independently, simulation C++ stl functors
package fs

type ComparerFileHash interface {
	F(left, right FileHash) bool
}

type ComparerFileHashCreator int

const (
	LESSER_FileHash ComparerFileHashCreator = iota
	GREATER_FileHash
)

func (me ComparerFileHashCreator) Create() (cmp ComparerFileHash) {
	switch me {
	case LESSER_FileHash:
		cmp = LesserFileHash(0)
	case GREATER_FileHash:
		cmp = GreaterFileHash(0)
	}
	return
}

type LesserFileHash byte

func (this LesserFileHash) F(left, right FileHash) (ok bool) {

	ok = left.Less(right)

	return
}

type GreaterFileHash byte

func (this GreaterFileHash) F(left, right FileHash) (ok bool) {

	ok = left > right

	return
}
