///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Wed Nov 02 2016 21:39:16]
// Generate from:
//   [github.com/vipally/gx/fs/tree.gp_filehash38b3.go]
//   [github.com/vipally/gx/fs/tree.gpg] [tree_filehash]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////



//this file define a template type for sort

<PACKAGE>

import "sort"



//func init() {
//	g<GLOBAL_NAME_PREFIX>SortSliceGbl.cmp = g<GLOBAL_NAME_PREFIX>SortSliceGbl.cmp.CreateByName("Greater")
//}

//var g<GLOBAL_NAME_PREFIX>SortSliceGbl struct {
//	cmp Cmp<GLOBAL_NAME_PART>
//}

//new sort object
func New<GLOBAL_NAME_PREFIX>SortSlice(capacity int, bigFirst bool) *<GLOBAL_NAME_PREFIX>SortSlice {
	p := &<GLOBAL_NAME_PREFIX>SortSlice{}
	p.Init(capacity, bigFirst)
	return p
}

//sort slice
type <GLOBAL_NAME_PREFIX>SortSlice struct {
	d   []<VALUE_TYPE>
	cmp Cmp<GLOBAL_NAME_PART>
}

//init
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Init(capacity int, bigFirst bool) {
	this.d = make([]<VALUE_TYPE>, 0, capacity)
	this.cmp = this.cmp.CreateByBool(bigFirst)
}

//sort
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Sort() {
	sort.Sort(this)
}

//data buffer
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Buffer() []<VALUE_TYPE> {
	return this.d
}

//push
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Push(v <VALUE_TYPE>) int {
	this.d = append(this.d, v)
	return this.Len()
}

//insert
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Insert(v <VALUE_TYPE>, idx int) int {
	if idx >= 0 && idx < this.Len() {
		right := this.d[idx+1:]
		this.d = append(this.d[:idx], v)
		this.d = append(this.d, right...)
	} else {
		this.d = append(this.d, v)
	}
	return this.Len()
}

//remove
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Remove(idx int) (ok bool) {
	if ok = idx >= 0 && idx < this.Len(); ok {
		right := this.d[idx+1:]
		this.d = append(this.d[:idx], right...)
	}
	return
}

//pop
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Pop() (r <VALUE_TYPE>, ok bool) {
	if ok = len(this.d) > 0; ok {
		r = (this.d)[len(this.d)-1]
	}
	this.d = (this.d)[:len(this.d)-1]
	return
}

//len
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Len() int {
	return len(this.d)
}

//sort by Hash decend,the larger one first
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Less(i, j int) (ok bool) {
	l, r := (this.d)[i], (this.d)[j]
	return this.cmp.F(l, r)
}

//swap
func (this *<GLOBAL_NAME_PREFIX>SortSlice) Swap(i, j int) {
	(this.d)[i], (this.d)[j] = (this.d)[j], (this.d)[i]
}

