///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Mon Oct 31 2016 23:52:23]
// Generate from:
//   [github.com/vipally/gx/fs/tree.gp_filehash38b3.go]
//   [github.com/vipally/gx/fs/tree.gpg] [tree_filehash]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
//
///////////////////////////////////////////////////////////////////

//this file define a template type for sort

package fs

import "sort"

func init() {
	gFileHashSortSliceGbl.cmp = gFileHashSortSliceGbl.cmp.CreateByName("Greater")
}

var gFileHashSortSliceGbl struct {
	cmp CmpFileHash
}

func NewFileHashSortSlice(bigFirst bool) *FileHashSortSlice {
	p := &FileHashSortSlice{}
	p.Init(bigFirst)
	return p
}

//for sort
type FileHashSortSlice struct {
	cmp CmpFileHash
	d   []FileHash
}

func (this *FileHashSortSlice) Init(bigFirst bool) {
	this.cmp = this.cmp.CreateByBool(bigFirst)
}

func (this *FileHashSortSlice) Sort() {
	sort.Sort(this)
}

//data
func (this *FileHashSortSlice) Slice() []FileHash {
	return this.d
}

//push
func (this *FileHashSortSlice) Push(v FileHash) int {
	this.d = append(this.d, v)
	return this.Len()
}

func (this *FileHashSortSlice) Pop() (r FileHash) {
	if len(this.d) > 0 {
		r = (this.d)[len(this.d)-1]
	}
	this.d = (this.d)[:len(this.d)-1]
	return
}

//len
func (this *FileHashSortSlice) Len() int {
	return len(this.Slice())
}

//sort by Hash decend,the larger one first
func (this *FileHashSortSlice) Less(i, j int) (ok bool) {
	l, r := (this.d)[i], (this.d)[j]
	return this.cmp.F(l, r)
}

//swap
func (this *FileHashSortSlice) Swap(i, j int) {
	(this.d)[i], (this.d)[j] = (this.d)[j], (this.d)[i]
}
