///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Sun Oct 30 2016 04:09:50]
// Generate from:
//   [github.com/vipally/gx/stl/gp/tree.gp]
//   [github.com/vipally/gx/fs/tree.gpg] [tree_filehash]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

//this file defines a template tree structure just like file system

package fs

import (
	"sort"
)

//tree strture
type FileHashTree struct {
	root *FileHashTreeNode
}

//new container
func NewFileHashTree() *FileHashTree {
	return &FileHashTree{}
}

//tree node
type FileHashTreeNode struct {
	FileHash
	children __FileHashTreeNodeSortSlice
}

func (this *FileHashTreeNode) SortChildren() {
	this.children.Sort()
}

func (this *FileHashTreeNode) Children() []*FileHashTreeNode {
	return this.children.Buffer()
}

//add a child
func (this *FileHashTreeNode) AddChild(v FileHash, idx int) (child *FileHashTreeNode) {
	n := &FileHashTreeNode{FileHash: v, children: nil}
	return this.AddChildNode(n, idx)
}

//add a child node
func (this *FileHashTreeNode) AddChildNode(node *FileHashTreeNode, idx int) (child *FileHashTreeNode) {
	if idx >= 0 && idx < len(this.children) {
		right := this.children[idx+1:]
		this.children = append(this.children[:idx], node)
		this.children = append(this.children, right...)
	} else {
		this.children = append(this.children, node)
	}
	return node
}

//cound of children
func (this *FileHashTreeNode) NumChildren() int {
	return len(this.children)
}

//get child
func (this *FileHashTreeNode) GetChild(idx int) (child *FileHashTreeNode, ok bool) {
	if ok = idx >= 0 && idx < len(this.children); ok {
		child = this.children[idx]
	}
	return
}

//remove child
func (this *FileHashTreeNode) RemoveChild(idx int) (child *FileHashTreeNode, ok bool) {
	if child, ok = this.GetChild(idx); ok {
		this.children = append(this.children[:idx], this.children[idx+1:]...)
	}
	return
}

//create a visitor
func (this *FileHashTreeNode) Visitor() (v *FileHashTreeNodeVisitor) {
	v = &FileHashTreeNodeVisitor{}
	v.push(this, -1)
	return
}

//get all node data
func (this *FileHashTreeNode) All() (list []FileHash) {
	list = append(list, this.FileHash)
	for _, v := range this.children {
		list = append(list, v.All()...)
	}
	return
}

//tree node visitor
type FileHashTreeNodeVisitor struct {
	node         *FileHashTreeNode
	parents      []*FileHashTreeNode
	brotherIdxes []int
	//visit order: this->child->brother
}

func (this *FileHashTreeNodeVisitor) push(n *FileHashTreeNode, bIdx int) {
	this.parents = append(this.parents, n)
	this.brotherIdxes = append(this.brotherIdxes, bIdx)
}

func (this *FileHashTreeNodeVisitor) pop() (n *FileHashTreeNode, bIdx int) {
	l := len(this.parents)
	if l > 0 {
		n, bIdx = this.tail()
		this.parents = this.parents[:l-1]
		this.brotherIdxes = this.brotherIdxes[:l-1]
	}
	return
}

func (this *FileHashTreeNodeVisitor) tail() (n *FileHashTreeNode, bIdx int) {
	l := len(this.parents)
	if l > 0 {
		n = this.parents[l-1]
		bIdx = this.brotherIdxes[l-1]
	}
	return
}

func (this *FileHashTreeNodeVisitor) depth() int {
	return len(this.parents)
}

func (this *FileHashTreeNodeVisitor) update_tail(bIdx int) bool {
	l := len(this.parents)
	if l > 0 {
		this.brotherIdxes[l-1] = bIdx
		return true
	}
	return false
}

func (this *FileHashTreeNodeVisitor) top_right(n *FileHashTreeNode) (p *FileHashTreeNode) {
	if n != nil {
		l := len(n.children)
		for l > 0 {
			this.push(n, l-1)
			n = n.children[l-1]
			l = len(n.children)
		}
		p = n
	}
	return
}

//visit next node
func (this *FileHashTreeNodeVisitor) Next() (data *FileHash, ok bool) {
	if this.node != nil { //check if has any children
		if len(this.node.children) > 0 {
			this.push(this.node, 0)
			this.node = this.node.children[0]
		} else {
			this.node = nil
		}
	}
	for this.node == nil && this.depth() > 0 { //check if has any brothers or uncles
		p, bIdx := this.tail()
		if bIdx < 0 { //ref parent
			this.node = p
			this.pop()
		} else if bIdx < len(p.children)-1 { //next brother
			bIdx++
			this.node = p.children[bIdx]
			this.update_tail(bIdx)
		} else { //no more brothers
			this.pop()
		}
	}
	if ok = this.node != nil; ok {
		data = this.Get()
	}
	return
}

//visit previous node
func (this *FileHashTreeNodeVisitor) Prev() (data *FileHash, ok bool) {
	if this.node == nil && this.depth() > 0 { //check if has any brothers or uncles
		p, _ := this.pop()
		this.node = this.top_right(p)
		if ok = this.node != nil; ok {
			data = this.Get()
		}
		return
	}

	if this.node != nil { //check if has any children
		p, bIdx := this.tail()
		if bIdx > 0 {
			bIdx--
			this.update_tail(bIdx)
			this.node = this.top_right(p.children[bIdx])
		} else {
			this.node = p
			this.pop()
		}
	}
	if ok = this.node != nil; ok {
		data = this.Get()
	}
	return
}

//get node data
func (this *FileHashTreeNodeVisitor) Get() *FileHash {
	return &this.node.FileHash
}

//for sort
type __FileHashTreeNodeSortSlice []*FileHashTreeNode

func (this *__FileHashTreeNodeSortSlice) Sort() {
	sort.Sort(this)
}

//data
func (this *__FileHashTreeNodeSortSlice) Buffer() []*FileHashTreeNode {
	return *this
}

//push
func (this *__FileHashTreeNodeSortSlice) Push(v *FileHashTreeNode) int {
	*this = append(*this, v)
	return this.Len()
}

func (this *__FileHashTreeNodeSortSlice) Pop() (r *FileHashTreeNode) {
	if len(*this) > 0 {
		r = (*this)[len(*this)-1]
	}
	*this = (*this)[:len(*this)-1]
	return
}

//len
func (this *__FileHashTreeNodeSortSlice) Len() int {
	return len(this.Buffer())
}

//sort by Hash decend,the larger one first
func (this *__FileHashTreeNodeSortSlice) Less(i, j int) (ok bool) {
	l, r := (*this)[i], (*this)[j]

	ok = l.Less(r.FileHash)

	return
}

//swap
func (this *__FileHashTreeNodeSortSlice) Swap(i, j int) {
	(*this)[i], (*this)[j] = (*this)[j], (*this)[i]
}
