///////////////////////////////////////////////////////////////////
//
//    !!!!!!!!!!NEVER MODIFY THIS FILE MANUALLY!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Wed Oct 05 2016 19:07:01]
// Generate from:
//     [github.com/vipally/gx/stl/tree.gp]
//     [github.com/vipally/gx/fs/tree.gpg] [file_hash]
//
//
//    CopyRight 2016 @Ally Dale. All rights reserved.
//		Author	: Ally Dale(vipally@gmail.com)
//		Blog	: http://blog.csdn.net/vipally
//		Site	: https://github.com/vipally
//		BuildAt	: [Oct  5 2016 12:17:48]
//		Version	: 2.9.0
///////////////////////////////////////////////////////////////////

//this file defines a template tree structure just like file system

package fs

import (
	"sort"
)

//tree node
type FileHashTreeNode struct {
	FileHash
	Children FileHashSortSlice
}

//create a visitor
func (this *FileHashTreeNode) Visitor() (v *FileHashTreeNodeVisitor) {
	v = &FileHashTreeNodeVisitor{}
	v.push(this, -1)
	return
}

//get all node data
func (this *FileHashTreeNode) All() (list []FileHash) {
	list = append(list, this.FileHash)
	for _, v := range this.Children {
		list = append(list, v.All()...)
	}
	return
}

//tree node visitor
type FileHashTreeNodeVisitor struct {
	node         *FileHashTreeNode
	parents      []*FileHashTreeNode
	brotherIdxes []int
	//visit order? this?child?brother?
}

func (this *FileHashTreeNodeVisitor) push(n *FileHashTreeNode, bIdx int) {
	this.parents = append(this.parents, n)
	this.brotherIdxes = append(this.brotherIdxes, bIdx)
}

func (this *FileHashTreeNodeVisitor) pop() (n *FileHashTreeNode, bIdx int) {
	l := len(this.parents)
	if l > 0 {
		n, bIdx = this.tail()
		this.parents = this.parents[:l-1]
		this.brotherIdxes = this.brotherIdxes[:l-1]
	}
	return
}

func (this *FileHashTreeNodeVisitor) tail() (n *FileHashTreeNode, bIdx int) {
	l := len(this.parents)
	if l > 0 {
		n = this.parents[l-1]
		bIdx = this.brotherIdxes[l-1]
	}
	return
}

func (this *FileHashTreeNodeVisitor) depth() int {
	return len(this.parents)
}

func (this *FileHashTreeNodeVisitor) update_tail(bIdx int) bool {
	l := len(this.parents)
	if l > 0 {
		this.brotherIdxes[l-1] = bIdx
		return true
	}
	return false
}

func (this *FileHashTreeNodeVisitor) top_right(n *FileHashTreeNode) (p *FileHashTreeNode) {
	if n != nil {
		l := len(n.Children)
		for l > 0 {
			this.push(n, l-1)
			n = n.Children[l-1]
			l = len(n.Children)
		}
		p = n
	}
	return
}

//visit next node
func (this *FileHashTreeNodeVisitor) Next() bool {
	if this.node != nil { //check if has any children
		if len(this.node.Children) > 0 {
			this.push(this.node, 0)
			this.node = this.node.Children[0]
		} else {
			this.node = nil
		}
	}
	for this.node == nil && this.depth() > 0 { //check if has any brothers or uncles
		p, bIdx := this.tail()
		if bIdx < 0 { //ref parent
			this.node = p
			this.pop()
		} else if bIdx < len(p.Children)-1 { //next brother
			bIdx++
			this.node = p.Children[bIdx]
			this.update_tail(bIdx)
		} else { //no more brothers
			this.pop()
		}
	}
	return this.node != nil
}

//visit previous node
func (this *FileHashTreeNodeVisitor) Prev() bool {
	if this.node == nil && this.depth() > 0 { //check if has any brothers or uncles
		p, _ := this.pop()
		this.node = this.top_right(p)
		return this.node != nil
	}

	if this.node != nil { //check if has any children
		p, bIdx := this.tail()
		if bIdx > 0 {
			bIdx--
			this.update_tail(bIdx)
			this.node = this.top_right(p.Children[bIdx])
		} else {
			this.node = p
			this.pop()
		}
	}
	return this.node != nil
}

//get node data
func (this *FileHashTreeNodeVisitor) Get() *FileHash {
	return &this.node.FileHash
}

//for sort
type FileHashSortSlice []*FileHashTreeNode

func (this *FileHashSortSlice) Sort() {
	sort.Sort(this)
}

//data
func (this *FileHashSortSlice) D() []*FileHashTreeNode {
	return *this
}

//push
func (this *FileHashSortSlice) Push(v *FileHashTreeNode) int {
	*this = append(*this, v)
	return this.Len()
}

func (this *FileHashSortSlice) Pop() (r *FileHashTreeNode) {
	if len(*this) > 0 {
		r = (*this)[len(*this)-1]
	}
	*this = (*this)[:len(*this)-1]
	return
}

//len
func (this *FileHashSortSlice) Len() int {
	return len(this.D())
}

//sort by Hash decend,the larger one first
func (this *FileHashSortSlice) Less(i, j int) bool {
	l, r := (*this)[i], (*this)[j]
	return l.Less(r.FileHash)
}

//swap
func (this *FileHashSortSlice) Swap(i, j int) {
	(*this)[i], (*this)[j] = (*this)[j], (*this)[i]
}

