///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Wed Nov 23 2016 23:06:35]
// Generate from:
//   [github.com/vipally/gx/stl/gp/heap.gp]
//   [github.com/vipally/gx/stl/stl.gpg] [heap_int]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

package stl

////////////////////////////////////////////////////////////////////////////////

type IntHeap struct {
	b      []int  //data buffer
	limitN int    //if limitN>0, heap size must<=limitN
	cmp    CmpInt //if top is max value
}

//new object
func NewIntHeap(capacity, limitN int, maxTop bool) (r *IntHeap) {
	r = &IntHeap{}
	r.Init(capacity, limitN, maxTop)
	return
}

//initialize
func (this *IntHeap) Init(capacity, limitN int, maxTop bool) {
	if cap(this.b) < capacity {
		this.b = make([]int, 0, capacity)
	}
	this.b = this.b[:0]

	this.limitN = limitN
	this.cmp = this.cmp.CreateByBool(!maxTop)
}

//push heap value
func (this *IntHeap) PushHeap(b []int, v int) []int {
	b = append(b, v)
	this.adjustUp(b, len(b)-1, v)
	return b
}

//pop heap top
func (this *IntHeap) PopHeap(b []int) (h []int, top int, ok bool) {
	l := len(b)
	if ok = l > 0; ok {
		top = b[0]
		if l > 1 {
			b[0], b[l-1] = b[l-1], b[0]
			this.adjustDown(b[:l-1], 0, b[0])
		}
		h = b[:l-1]
	}
	return
}

//check if b is a valid heap
func (this *IntHeap) CheckHeap(b []int) bool {
	for i := len(b) - 1; i > 0; i-- {
		p := this.parent(i)
		if !this.cmpV(b[i], b[p]) {
			return false
		}
	}
	return true
}

//adjust heap to select a proper hole to set v
func (this *IntHeap) adjustDown(b []int, hole int, v int) {
	size := len(b)

	//try to improve STL's adjust down algorithm
	//adjust heap to select a proper hole to set v
	for l := this.lchild(hole); l < size; l = this.lchild(hole) {
		c := l                                              //index that need compare with hole
		if r := l + 1; r < size && !this.cmpV(b[r], b[l]) { //let the most proper child to compare with v
			c = r
		}
		if this.cmpV(b[c], v) { //v is the most proper root, finish adjust
			break
		} else { //c is the most proper root, swap with hole, and continue adjust
			b[hole], hole = b[c], c
		}
	}
	b[hole] = v //put v to last hole

}

//adjust heap to select a proper hole to set v
func (this *IntHeap) adjustUp(b []int, hole int, v int) {
	for hole > 0 {
		if parent := this.parent(hole); !this.cmpV(v, b[parent]) {
			b[hole], hole = b[parent], parent
		} else {
			break
		}
	}
	b[hole] = v //put v to last hole
}

//make b as a heap
func (this *IntHeap) MakeHeap(b []int) {
	if l := len(b); l > 1 {
		for i := l / 2; i >= 0; i-- {
			this.adjustDown(b, i, b[i])
		}
	}
}

//reverse order of b
func (this *IntHeap) Reverse(b []int) {
	l := len(b) - 1
	for i := l / 2; i >= 0; i-- {
		b[i], b[l-i] = b[l-i], b[i]
	}
}

//sort slice use heap algorithm
func (this *IntHeap) SortHeap(b []int) []int {
	this.MakeHeap(b)
	for t := b; len(t) > 1; {
		t, _, _ = this.PopHeap(t)
	}
	return b
}

//heap slice
func (this *IntHeap) Buffer() []int {
	return this.b
}

//push
func (this *IntHeap) Push(v int) {
	if this.limitN > 0 && this.Size() >= this.limitN {
		if top, ok := this.Top(); ok && this.cmpV(v, top) {
			this.Pop()
		} else {
			return
		}
	}
	this.b = this.PushHeap(this.b, v)
}

//pop
func (this *IntHeap) Pop() (top int, ok bool) {
	this.b, top, ok = this.PopHeap(this.b)
	return
}

//heap top
func (this *IntHeap) Top() (top int, ok bool) {
	if ok = !this.Empty(); ok {
		top = this.b[0]
	}
	return
}

//cmpare value
func (this *IntHeap) cmpV(c, p int) (ok bool) {
	ok = !this.cmp.F(p, c)
	return
}

//get parent index
func (this *IntHeap) parent(idx int) int {
	return (idx - 1) / 2
}

//get left child index
func (this *IntHeap) lchild(idx int) int {
	return 2*idx + 1
}

//get right child index
//func (this *GOGPHeapNamePrefixHeap) rchild(idx int) int {
//	return 2*idx + 2
//}

//func (this *GOGPHeapNamePrefixHeap) children(idx int) (l, r int) {
//	l = 2*idx + 1
//	r = l + 1
//	return
//}

//size
func (this *IntHeap) Size() int {
	return len(this.b)
}

//empty
func (this *IntHeap) Empty() bool {
	return this.Size() == 0
}
