///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Wed Nov 23 2016 22:25:30]
// Generate from:
//   [github.com/vipally/gx/stl/gp/sort_slice.gp]
//   [github.com/vipally/gx/stl/stl.gpg] [sort_slice_int]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

//this file define a template type for sort

package stl

import "sort"

////////////////////////////////////////////////////////////////////////////////

var gIntSortSliceGbl struct {
	cmp CmpInt
}

func init() {
	gIntSortSliceGbl.cmp = gIntSortSliceGbl.cmp.CreateByName("")
}

//new sort object
func NewIntSortSlice(capacity int) *IntSortSlice {
	p := &IntSortSlice{}
	p.Init(capacity)
	return p
}

//sort slice
type IntSortSlice struct {
	d []int
}

//init
func (this *IntSortSlice) Init(capacity int) {
	this.d = make([]int, 0, capacity)
}

//sort
func (this *IntSortSlice) Sort() {
	sort.Sort(this)
}

//data buffer
func (this *IntSortSlice) Buffer() []int {
	return this.d
}

//push
func (this *IntSortSlice) Push(v int) int {
	this.d = append(this.d, v)
	return this.Len()
}

//insert
func (this *IntSortSlice) Insert(v int, idx int) int {
	if idx >= 0 && idx < this.Len() {
		right := this.d[idx+1:]
		this.d = append(this.d[:idx], v)
		this.d = append(this.d, right...)
	} else {
		this.d = append(this.d, v)
	}
	return this.Len()
}

//remove
func (this *IntSortSlice) Remove(idx int) (r int, ok bool) {
	if r, ok = this.Get(idx); ok {
		right := this.d[idx+1:]
		this.d = append(this.d[:idx], right...)
	}
	return
}

//pop
func (this *IntSortSlice) Pop() (r int, ok bool) {
	if ok = len(this.d) > 0; ok {
		r = (this.d)[len(this.d)-1]
	}
	this.d = (this.d)[:len(this.d)-1]
	return
}

//get
func (this *IntSortSlice) Get(idx int) (r int, ok bool) {
	if ok = idx >= 0 && idx < this.Len(); ok {
		r = this.d[idx]
	}
	return
}

//must get
func (this *IntSortSlice) MustGet(idx int) (r int) {
	ok := false
	if r, ok = this.Get(idx); !ok {
		panic(idx)
	}
	return
}

//len
func (this *IntSortSlice) Len() int {
	return len(this.d)
}

//sort by Hash decend,the larger one first
func (this *IntSortSlice) Less(i, j int) (ok bool) {
	l, r := (this.d)[i], (this.d)[j]
	return gIntSortSliceGbl.cmp.F(l, r)
}

//swap
func (this *IntSortSlice) Swap(i, j int) {
	(this.d)[i], (this.d)[j] = (this.d)[j], (this.d)[i]
}
