///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Wed Nov 23 2016 22:22:58]
// Generate from:
//   [github.com/vipally/gx/stl/gp/stack.gp]
//   [github.com/vipally/gx/stl/stl.gpg] [stack_int]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct 24 2016 20:25:45]
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

package stl

////////////////////////////////////////////////////////////////////////////////

//stack object
type IntStack struct {
	d []int
}

//new object
func NewGOGPStackNamePrefixStack(bufSize int) *IntStack {
	r := &IntStack{}
	r.Init(bufSize)
	return r
}

//init
func (this *IntStack) Init(bufSize int) {
	if nil == this.d {
		if -1 == bufSize {
			bufSize = 10
		}
		if bufSize > 0 {
			this.d = make([]int, 0, bufSize)
		}
	}
	this.d = this.d[:0]
	return
}

//clear
func (this *IntStack) Clear() {
	this.Init(-1)
}

//push v to top of stack
func (this *IntStack) Push(v int) (ok bool) {
	if ok = true; ok {
		this.d = append(this.d, v)
	}
	return
}

//pop top of stack
func (this *IntStack) Pop() (top int, ok bool) {
	if top, ok = this.Top(); ok {
		this.d = this.d[:this.Size()-1]
	}
	return
}

//get top of stack
func (this *IntStack) Top() (top int, ok bool) {
	d := this.Size()
	if d > 0 {
		top = this.d[d-1]
		ok = true
	}
	return

}

//size of stack
func (this *IntStack) Size() int {
	return len(this.d)
}

//is stack is empty
func (this *IntStack) Empty() bool {
	return this.Size() == 0
}

////show
//func (this *IntStack) Show() string {
//	var b show_bytes.Buffer
//	b.WriteByte('[')
//	for _, v := range this.d {
//		b.WriteString(v.Show())
//		b.WriteByte(',')
//	}
//	if this.Size() > 0 {
//		b.Truncate(b.Len() - 1) //remove last ','
//	}
//	b.WriteByte(']')
//	return b.String()
//} //
