///////////////////////////////////////////////////////////////////
//
//    !!!!!!!!!!NEVER MODIFY THIS FILE MANUALLY!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Wed Sep 28 2016 16:02:09]
// Generate from:
//     [github.com/vipally/gx/regable/reg.gp]
//     [github.com/vipally/gx/regable/reg.gpg] [iter]
//
//
//    CopyRight 2016 @Ally Dale. All rights reserved.
//    Use of this source code is governed by a GPL3.0-style.
//    License that can be found in the LICENSE file.
//    Author  : Ally Dale(vipally@gmail.com)
//    Blog    : http://blog.csdn.net/vipally
//    Site    : https://github.com/vipally
//    BuildAt : [Sep 27 2016 16:45:53]
//    Version : 2.1.0
///////////////////////////////////////////////////////////////////

package regable

import (
	"bytes"
	"fmt"
	"sync"
	"github.com/vipally/gx/consts"
	"github.com/vipally/gx/errors"
	xmath "github.com/vipally/gx/math"
)

const (
	default_iter_reg_cnt = 1024
)

var (
	g_iter_rgr_id_gen, _         = amath.NewRangeUint32(g_invalid_id+1, g_invalid_id, g_max_reger_id)
	errid_iter_id, _  = aerr.Reg("InerfaceId error")
	errid_iter_obj, _ = aerr.Reg("Inerface object error")
)

var (
	g_iter_reger_list []*InerfaceReger
)

func init() {
	reg_show(ShowAllInerfaceRegers)
}

//new reger
func NewInerfaceReger(name string) (r *InerfaceReger, err error) {
	defer func() {
		if err != nil {
			panic(err)
		}
	}()
	if err = check_lock(); err != nil {
		return
	}
	id := g_invalid_id
	if id, err = g_iter_rgr_id_gen.Inc(); err != nil {
		return
	}
	p := new(InerfaceReger)
	if err = p.init(name); err == nil {
		p.reger_id = uint8(id)
		r = p
		g_iter_reger_list = append(g_iter_reger_list, p)
	}
	return
}

func MustNewInerfaceReger(name string) (r *InerfaceReger) {
	if reg, err := NewInerfaceReger(name); err != nil {
		panic(err)
	} else {
		r = reg
	}
	return
}

//show all regers
func ShowAllInerfaceRegers() string {
	var buf bytes.Buffer
	s := fmt.Sprintf("[InerfaceRegers] count:%d", len(g_iter_reger_list))
	buf.WriteString(s)
	for _, v := range g_iter_reger_list {
		buf.WriteString(consts.NewLine)
		buf.WriteString(v.String())
	}
	return buf.String()
}

//reger object
type InerfaceReger struct {
	reger_id uint8
	name     string
	id_gen   amath.RangeUint32
	reg_list []*_interfaceRecord
}

func (me *InerfaceReger) init(name string) (err error) {
	me.name = name
	if err = me.id_gen.Init(g_invalid_id+1, g_invalid_id,
		g_invalid_id+default_iter_reg_cnt); err != nil {
		return
	}
	me.reg_list = make([]*_interfaceRecord, 0, 0)
	return
}

//set max reg count at a reger
func (me *InerfaceReger) MaxReg(max_regs uint32) (rmax uint32, err error) {
	if err = verify_max_regs(max_regs); err != nil {
		return
	}
	cur, min, _ := me.id_gen.Get()
	if err = me.id_gen.Init(cur, min, g_invalid_id+max_regs); err != nil {
		return
	}
	rmax = me.id_gen.Max()
	return
}

//reg a value
func (me *InerfaceReger) Reg(name string, val interface{}) (r InerfaceId, err error) {
	r = InerfaceId(g_invalid_id)
	defer func() {
		if err != nil {
			panic(err)
		}
	}()
	id := g_invalid_id
	if err = check_lock(); err != nil {
		return
	}
	if id, err = me.id_gen.Inc(); err != nil {
		return
	}
	p := me.new_rec(name, val)
	p.id = id
	me.reg_list = append(me.reg_list, p)
	r = InerfaceId(MakeRegedId(uint32(me.reger_id), id))
	return
}

func (me *InerfaceReger) MustReg(name string, val interface{}) (r InerfaceId) {
	if reg, err := me.Reg(name, val); err != nil {
		panic(err)
	} else {
		r = reg
	}
	return
}

//show string
func (me *InerfaceReger) String() string {
	var buf bytes.Buffer
	s := fmt.Sprintf("[InerfaceReger#%d: %s] ids:%s",
		me.reger_id, me.name, me.id_gen.String())
	buf.WriteString(s)
	for i, v := range me.reg_list {
		v.lock.RLock()
		s = fmt.Sprintf("\n#%d [%s]: %v",
			uint32(i)+g_invalid_id+1, v.name,
			v.val)
		v.lock.RUnlock()
		buf.WriteString(s)
	}
	return buf.String()
}

type _interfaceRecord struct {
	name string
	val  interface{}
	id   uint32
	lock sync.RWMutex
}

func (me *InerfaceReger) new_rec(name string, val interface{}) (r *_interfaceRecord) {
	r = new(_interfaceRecord)
	r.name = name
	r.val = val
	return
}

type InerfaceId regedId

func (cp InerfaceId) get() (rg *InerfaceReger, r *_interfaceRecord, err error) {
	idrgr, id := regedId(cp).ids()
	idregidx, idx := idrgr-g_invalid_id-1, id-g_invalid_id-1
	if idrgr == g_invalid_id || !g_iter_rgr_id_gen.InCurrentRange(idrgr) {
		err = aerr.New(errid_iter_id)
	}
	rg = g_iter_reger_list[idregidx]
	if id == g_invalid_id || !rg.id_gen.InCurrentRange(id) {
		err = aerr.New(errid_iter_id)
	}
	r = rg.reg_list[idx]
	return
}

//check if valid
func (cp InerfaceId) Valid() (rvalid bool) {
	if _, _, e := cp.get(); e == nil {
		rvalid = true
	}
	return
}

//get value
func (cp InerfaceId) Get() (r interface{}, err error) {
	_, rc, e := cp.get()
	if e != nil {
		return r, e
	}
	return rc.Get()
}

//get value with out error, if has error will cause panic
func (cp InerfaceId) GetNoErr() (r interface{}) {
	_, rc, e := cp.get()
	if e != nil {
		panic(e.Error())
	}
	return rc.GetNoErr()
}

//set value
func (cp InerfaceId) Set(val interface{}) (r interface{}, err error) {
	_, rc, e := cp.get()
	if e != nil {
		return r, e
	}
	return rc.Set(val)
}

//reverse bool value(as a switch)
//func (cp InerfaceId) Reverse() (r interface{}, err error) {
//	_, rc, e := cp.get()
//	if e != nil {
//		return r, e
//	}
//	return rc.Reverse()
//}

//get reger_id and real_id
func (cp InerfaceId) Ids() (reger_id, real_id uint32) {
	return regedId(cp).ids()
}

//show string
func (cp InerfaceId) String() (r string) {
	idrgr, id := regedId(cp).ids()
	_, rc, err := cp.get()
	if err != nil {
		r = fmt.Sprintf("invalid InerfaceId#(%d|%d)", idrgr, id)
	} else {
		r = rc.String()
	}
	return
}

//get name

func (cp InerfaceId) Name() (r string, err error) {
	_, rc, e := cp.get()
	if e == nil {
		r, err = rc.Name()
	} else {
		err = e
	}
	return
}


//get as object for fast access
func (cp InerfaceId) Oject() (r InerfaceObj) {
	_, rc, e := cp.get()
	if e == nil {
		r.obj = rc
	}
	return
}

//get name

func (me *_interfaceRecord) Name() (r string, err error) {
	if me != nil {
		me.lock.RLock()
		defer me.lock.RUnlock()
		r = me.name
	} else {
		err = aerr.New(errid_iter_obj)
	}
	return
}


//get value
func (me *_interfaceRecord) Get() (r interface{}, err error) {
	if me != nil {
		me.lock.RLock()
		defer me.lock.RUnlock()
		r = me.val
	} else {
		err = aerr.New(errid_iter_obj)
	}
	return
}

//get value without error,if has error will cause panic
func (me *_interfaceRecord) GetNoErr() (r interface{}) {
	r0, err := me.Get()
	if err != nil {
		panic(err.Error())
	}
	r = r0
	return
}

//set value
func (me *_interfaceRecord) Set(val interface{}) (r interface{}, err error) {
	if nil != me {
		me.lock.Lock()
		defer me.lock.Unlock()
		me.val = val
		r = val
	} else {
		err = aerr.New(errid_iter_obj)
	}
	return
}

//reverse on bool value
//func (me *_interfaceRecord) Reverse() (r interface{}, err error) {
//	if nil != me {
//		me.lock.Lock()
//		defer me.lock.Unlock()
//		me.val = !me.val
//		r = me.val
//	} else {
//		err = aerr.New(errid_iter_obj)
//	}
//	return
//}

//get as Id
func (me *_interfaceRecord) Id() (r InerfaceId) {
	if me != nil {
		r = InerfaceId(me.id)
	}
	return
}

//show string
func (me *_interfaceRecord) String() (r string) {
	if me != nil {
		idrgr, id := regedId(me.id).ids()
		me.lock.RLock()
		defer me.lock.RUnlock()
		r = fmt.Sprintf("Inerface#(%d|%d|%s)%v", idrgr, id, me.name, me.val)
	} else {
		r = fmt.Sprintf("invalid interface{} object")
	}
	return
}

//object of reged value,it is more efficient to access than Id object
type InerfaceObj struct {
	obj *_interfaceRecord
}

//check if valid
func (cp InerfaceObj) Valid() (rvalid bool) {
	return cp.obj != nil
}

//get value
func (cp InerfaceObj) Get() (r interface{}, err error) {
	return cp.obj.Get()
}

//get value against error,if has error will cause panic
func (cp InerfaceObj) GetNoErr() (r interface{}) {
	return cp.obj.GetNoErr()
}

//set value
func (cp InerfaceObj) Set(val interface{}) (r interface{}, err error) {
	return cp.obj.Set(val)
}

//reverse bool object
//func (cp InerfaceObj) Reverse() (r interface{}, err error) {
//	return cp.obj.Reverse()
//}

//show string
func (cp InerfaceObj) String() (r string) {
	return cp.obj.String()
}

//get name

func (cp InerfaceObj) Name() (r string, err error) {
	return cp.obj.Name()
}


//get as Id
func (cp InerfaceObj) Id() (r InerfaceId) {
	return cp.obj.Id()
}

//reg and return an object agent
func (me *InerfaceReger) RegO(name string, val interface{}) (r InerfaceObj, err error) {
	id, e := me.Reg(name, val)
	if e == nil {
		r = id.Oject()
	} else {
		err = e
	}
	return
}

func (me *InerfaceReger) MustRegO(name string, val interface{}) (r InerfaceObj) {
	if reg, err := me.RegO(name, val); err != nil {
		panic(err)
	} else {
		r = reg
	}
	return
}
