///////////////////////////////////////////////////////////////////
//
// !!!!!!!!!!!! NEVER MODIFY THIS FILE MANUALLY !!!!!!!!!!!!
//
// This file was auto-generated by tool [github.com/vipally/gogp]
// Last update at: [Fri Oct 07 2016 17:37:46]
// Generate from:
//   [github.com/vipally/gx/regable/reg.gp]
//   [github.com/vipally/gx/regable/reg.gpg] [cu32]
//
// Tool [github.com/vipally/gogp] info:
// CopyRight 2016 @Ally Dale. All rights reserved.
// Author  : Ally Dale(vipally@gmail.com)
// Blog    : http://blog.csdn.net/vipally
// Site    : https://github.com/vipally
// BuildAt : [Oct  6 2016 14:25:07]
// Version : 3.0.0.final
// 
///////////////////////////////////////////////////////////////////

package regable

import (
	"bytes"
	"fmt"
	//"sync"
	"github.com/vipally/gx/consts"
	"github.com/vipally/gx/errors"
	xmath "github.com/vipally/gx/math"
)

const (
	default_const_u32_reg_cnt = 1024
)

var (
	g_const_u32_rgr_id_gen, _         = amath.NewRangeUint32(g_invalid_id+1, g_invalid_id, g_max_reger_id)
	errid_const_u32_id, _  = aerr.Reg("ConstUint32Id error")
	errid_const_u32_obj, _ = aerr.Reg("ConstUint32 object error")
)

var (
	g_const_u32_reger_list []*ConstUint32Reger
)

func init() {
	reg_show(ShowAllConstUint32Regers)
}

//new reger
func NewConstUint32Reger(name string) (r *ConstUint32Reger, err error) {
	defer func() {
		if err != nil {
			panic(err)
		}
	}()
	if err = check_lock(); err != nil {
		return
	}
	id := g_invalid_id
	if id, err = g_const_u32_rgr_id_gen.Inc(); err != nil {
		return
	}
	p := new(ConstUint32Reger)
	if err = p.init(name); err == nil {
		p.reger_id = uint8(id)
		r = p
		g_const_u32_reger_list = append(g_const_u32_reger_list, p)
	}
	return
}

func MustNewConstUint32Reger(name string) (r *ConstUint32Reger) {
	if reg, err := NewConstUint32Reger(name); err != nil {
		panic(err)
	} else {
		r = reg
	}
	return
}

//show all regers
func ShowAllConstUint32Regers() string {
	var buf bytes.Buffer
	s := fmt.Sprintf("[ConstUint32Regers] count:%d", len(g_const_u32_reger_list))
	buf.WriteString(s)
	for _, v := range g_const_u32_reger_list {
		buf.WriteString(consts.NewLine)
		buf.WriteString(v.String())
	}
	return buf.String()
}

//reger object
type ConstUint32Reger struct {
	reger_id uint8
	name     string
	id_gen   amath.RangeUint32
	reg_list []*_const_uint32Record
}

func (me *ConstUint32Reger) init(name string) (err error) {
	me.name = name
	if err = me.id_gen.Init(g_invalid_id+1, g_invalid_id,
		g_invalid_id+default_const_u32_reg_cnt); err != nil {
		return
	}
	me.reg_list = make([]*_const_uint32Record, 0, 0)
	return
}

//set max reg count at a reger
func (me *ConstUint32Reger) MaxReg(max_regs uint32) (rmax uint32, err error) {
	if err = verify_max_regs(max_regs); err != nil {
		return
	}
	cur, min, _ := me.id_gen.Get()
	if err = me.id_gen.Init(cur, min, g_invalid_id+max_regs); err != nil {
		return
	}
	rmax = me.id_gen.Max()
	return
}

//reg a value
func (me *ConstUint32Reger) Reg(name string, val uint32) (r ConstUint32Id, err error) {
	r = ConstUint32Id(g_invalid_id)
	defer func() {
		if err != nil {
			panic(err)
		}
	}()
	id := g_invalid_id
	if err = check_lock(); err != nil {
		return
	}
	if id, err = me.id_gen.Inc(); err != nil {
		return
	}
	p := me.new_rec(name, val)
	p.id = id
	me.reg_list = append(me.reg_list, p)
	r = ConstUint32Id(MakeRegedId(uint32(me.reger_id), id))
	return
}

func (me *ConstUint32Reger) MustReg(name string, val uint32) (r ConstUint32Id) {
	if reg, err := me.Reg(name, val); err != nil {
		panic(err)
	} else {
		r = reg
	}
	return
}

//show string
func (me *ConstUint32Reger) String() string {
	var buf bytes.Buffer
	s := fmt.Sprintf("[ConstUint32Reger#%d: %s] ids:%s",
		me.reger_id, me.name, me.id_gen.String())
	buf.WriteString(s)
	for i, v := range me.reg_list {
		//v.lock.RLock()
		s = fmt.Sprintf("\n#%d [%s]: %v",
			uint32(i)+g_invalid_id+1, v.name,
			v.val)
		//v.lock.RUnlock()
		buf.WriteString(s)
	}
	return buf.String()
}

type _const_uint32Record struct {
	name string
	val  uint32
	id   uint32
	//lock sync.RWMutex
}

func (me *ConstUint32Reger) new_rec(name string, val uint32) (r *_const_uint32Record) {
	r = new(_const_uint32Record)
	r.name = name
	r.val = val
	return
}

type ConstUint32Id regedId

func (cp ConstUint32Id) get() (rg *ConstUint32Reger, r *_const_uint32Record, err error) {
	idrgr, id := regedId(cp).ids()
	idregidx, idx := idrgr-g_invalid_id-1, id-g_invalid_id-1
	if idrgr == g_invalid_id || !g_const_u32_rgr_id_gen.InCurrentRange(idrgr) {
		err = aerr.New(errid_const_u32_id)
	}
	rg = g_const_u32_reger_list[idregidx]
	if id == g_invalid_id || !rg.id_gen.InCurrentRange(id) {
		err = aerr.New(errid_const_u32_id)
	}
	r = rg.reg_list[idx]
	return
}

//check if valid
func (cp ConstUint32Id) Valid() (rvalid bool) {
	if _, _, e := cp.get(); e == nil {
		rvalid = true
	}
	return
}

//get value
func (cp ConstUint32Id) Get() (r uint32, err error) {
	_, rc, e := cp.get()
	if e != nil {
		return r, e
	}
	return rc.Get()
}

//get value with out error, if has error will cause panic
func (cp ConstUint32Id) GetNoErr() (r uint32) {
	_, rc, e := cp.get()
	if e != nil {
		panic(e.Error())
	}
	return rc.GetNoErr()
}

//set value
//func (cp ConstUint32Id) Set(val uint32) (r uint32, err error) {
//	_, rc, e := cp.get()
//	if e != nil {
//		return r, e
//	}
//	return rc.Set(val)
//}

//reverse bool value(as a switch)
//func (cp ConstUint32Id) Reverse() (r uint32, err error) {
//	_, rc, e := cp.get()
//	if e != nil {
//		return r, e
//	}
//	return rc.Reverse()
//}

//get reger_id and real_id
func (cp ConstUint32Id) Ids() (reger_id, real_id uint32) {
	return regedId(cp).ids()
}

//show string
func (cp ConstUint32Id) String() (r string) {
	idrgr, id := regedId(cp).ids()
	_, rc, err := cp.get()
	if err != nil {
		r = fmt.Sprintf("invalid ConstUint32Id#(%d|%d)", idrgr, id)
	} else {
		r = rc.String()
	}
	return
}

//get name

func (cp ConstUint32Id) Name() (r string, err error) {
	_, rc, e := cp.get()
	if e == nil {
		r, err = rc.Name()
	} else {
		err = e
	}
	return
}


//get as object for fast access
func (cp ConstUint32Id) Oject() (r ConstUint32Obj) {
	_, rc, e := cp.get()
	if e == nil {
		r.obj = rc
	}
	return
}

//get name

func (me *_const_uint32Record) Name() (r string, err error) {
	if me != nil {
//		me.lock.RLock()
//		defer me.lock.RUnlock()
		r = me.name
	} else {
		err = aerr.New(errid_const_u32_obj)
	}
	return
}


//get value
func (me *_const_uint32Record) Get() (r uint32, err error) {
	if me != nil {
//		me.lock.RLock()
//		defer me.lock.RUnlock()
		r = me.val
	} else {
		err = aerr.New(errid_const_u32_obj)
	}
	return
}

//get value without error,if has error will cause panic
func (me *_const_uint32Record) GetNoErr() (r uint32) {
	r0, err := me.Get()
	if err != nil {
		panic(err.Error())
	}
	r = r0
	return
}

//set value
//func (me *_const_uint32Record) Set(val uint32) (r uint32, err error) {
//	if nil != me {
//		me.lock.Lock()
//		defer me.lock.Unlock()
//		me.val = val
//		r = val
//	} else {
//		err = aerr.New(errid_const_u32_obj)
//	}
//	return
//}

//reverse on bool value
//func (me *_const_uint32Record) Reverse() (r uint32, err error) {
//	if nil != me {
////		me.lock.Lock()
////		defer me.lock.Unlock()
//		me.val = !me.val
//		r = me.val
//	} else {
//		err = aerr.New(errid_const_u32_obj)
//	}
//	return
//}

//get as Id
func (me *_const_uint32Record) Id() (r ConstUint32Id) {
	if me != nil {
		r = ConstUint32Id(me.id)
	}
	return
}

//show string
func (me *_const_uint32Record) String() (r string) {
	if me != nil {
		idrgr, id := regedId(me.id).ids()
//		me.lock.RLock()
//		defer me.lock.RUnlock()
		r = fmt.Sprintf("ConstUint32#(%d|%d|%s)%v", idrgr, id, me.name, me.val)
	} else {
		r = fmt.Sprintf("invalid uint32 object")
	}
	return
}

//object of reged value,it is more efficient to access than Id object
type ConstUint32Obj struct {
	obj *_const_uint32Record
}

//check if valid
func (cp ConstUint32Obj) Valid() (rvalid bool) {
	return cp.obj != nil
}

//get value
func (cp ConstUint32Obj) Get() (r uint32, err error) {
	return cp.obj.Get()
}

//get value against error,if has error will cause panic
func (cp ConstUint32Obj) GetNoErr() (r uint32) {
	return cp.obj.GetNoErr()
}

//set value
//func (cp ConstUint32Obj) Set(val uint32) (r uint32, err error) {
//	return cp.obj.Set(val)
//}

//reverse bool object
//func (cp ConstUint32Obj) Reverse() (r uint32, err error) {
//	return cp.obj.Reverse()
//}

//show string
func (cp ConstUint32Obj) String() (r string) {
	return cp.obj.String()
}

//get name

func (cp ConstUint32Obj) Name() (r string, err error) {
	return cp.obj.Name()
}


//get as Id
func (cp ConstUint32Obj) Id() (r ConstUint32Id) {
	return cp.obj.Id()
}

//reg and return an object agent
func (me *ConstUint32Reger) RegO(name string, val uint32) (r ConstUint32Obj, err error) {
	id, e := me.Reg(name, val)
	if e == nil {
		r = id.Oject()
	} else {
		err = e
	}
	return
}

func (me *ConstUint32Reger) MustRegO(name string, val uint32) (r ConstUint32Obj) {
	if reg, err := me.RegO(name, val); err != nil {
		panic(err)
	} else {
		r = reg
	}
	return
}
